# Generated by Django 4.0.3 on 2022-05-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_autor_categoria_delete_curso_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Categoría Activada/Categoría no Activada'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=-3, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
    ]
