# Generated by Django 4.0.3 on 2022-05-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_categoria_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fecha_creacion',
        ),
    ]
