# Generated by Django 4.0.3 on 2022-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default=None, verbose_name='Contenido'),
        ),
    ]
